name: Docker Image Build + Push

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:

  build:
    if: github.repository == 'lyraproj/hiera'
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out repo
      uses: actions/checkout@master
    - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: lyraproj/hiera
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
